front sledi smeri rotacije koles in je glavni 
zadek je v bistvu samo kdaj se obrne cel sprite
kolesa so rotirana kot glede na zadek 
va aree nazaj štetje boltov

šild se spawna posebej
bolt_id > player_id
rear ime

malo še uredi poimenovanja (trivia
magnet brick ima drugo logiko (point gravity
trenutno samo barva .... funkcionalnosti še popedenaj
testiraj zaznavanje

PRINTAJ
DIZAJN
MINA TJA MINA NAZAJ
TELEKOM
BASKET
